# Generated by Django 6.0.2 on 2026-03-16 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured'),
        ),
        migrations.AddField(
            model_name='estateagent',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='estateagentcomment',
            name='stars_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Stars Count'),
        ),
    ]
