# Generated by Django 6.0.2 on 2026-03-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_estate_is_featured_estateagent_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
